import Link from "next/link";
import SearchBar from "@/components/SearchBar";
import { listPrecachedOrgs } from "@/lib/cache";

export default function Home() {
  const quickPicks = listPrecachedOrgs();

  return (
    <main className="flex min-h-screen flex-col items-center px-4 py-16 sm:py-24">
      <div className="w-full max-w-2xl text-center">
        <p
          className="mb-3 inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-medium"
          style={{ background: "rgba(42,120,214,0.1)", color: "var(--series-1)" }}
        >
          Overhead Myth Buster
        </p>
        <h1 className="mb-4 text-3xl font-bold leading-tight sm:text-4xl" style={{ color: "var(--text-primary)" }}>
          GlassPocket
        </h1>
        <p className="mx-auto mb-8 max-w-xl text-base leading-relaxed" style={{ color: "var(--text-secondary)" }}>
          Most charity-rating tools score you on the &quot;overhead ratio&quot; — how little you spend on staff
          and infrastructure. That heuristic is backwards, and often not even computable from clean data.
          Search a US 501(c)(3) and see what its IRS Form 990 history actually shows.
        </p>

        <div className="flex justify-center">
          <SearchBar />
        </div>

        {quickPicks.length > 0 && (
          <div className="mt-8">
            <p className="mb-3 text-xs font-medium uppercase tracking-wide" style={{ color: "var(--text-muted)" }}>
              Or try one of these
            </p>
            <div className="flex flex-wrap justify-center gap-2">
              {quickPicks.map((org) => (
                <Link
                  key={org.ein}
                  href={`/charity/${org.ein}`}
                  className="rounded-full border px-3.5 py-1.5 text-sm transition-colors hover:opacity-80"
                  style={{ borderColor: "var(--border-hairline)", color: "var(--text-primary)", background: "var(--surface-1)" }}
                >
                  {org.name}
                </Link>
              ))}
            </div>
          </div>
        )}
      </div>

      <footer className="mt-16 max-w-xl text-center text-xs" style={{ color: "var(--text-muted)" }}>
        Financial data via ProPublica Nonprofit Explorer (IRS Form 990 e-filings). Narrative generated by an LLM
        under a strict rubric, or a deterministic fallback when no model is available — never invented numbers.
      </footer>
    </main>
  );
}
